# The port to listen on, with a colon in front of it
Port = ":9001"

# The address:port to send to when the clipboard changes
Server = "192.168.1.5:9001"

# Mode to run in.
# 1 = Client
# 2 = Server
# 3 = both
Mode = 1